apiVersion: v1
kind: Service
metadata:
  name: hotstarsvc
  namespace: test
spec:
  type: ClusterIP
  selector:
    app: hotstarapp
  ports:
  - port: 80
    targetPort: 3000
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotstardeployment
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotstarapp
  template:
    metadata:
      labels:
        app: hotstarapp
    spec:
      containers:
      - name: hotstarcontainer
        image: dixit7/hotstar:v1
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"
            memory: "150Mi"
          limits:
            cpu: "500m"
            memory: "700Mi"
